# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Abby Krishnan
tagline:          'Welcome!'
description:      'I'm a computer science student at UT who loves politics, food, and tech!'
url:              abbykrish.github.io
baseurl:          /

author:
  name:           'Abby Krishnan'
  url:            https://twitter.com/abbykrish

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
